name: s3test
version: 1.2
summary: Test RadosGW S3 API 
description: >
   This package provides an easy way to upload random data to an S3 API
   provided by a Ceph Rados Gateway. It requires Openstack Keystone for
   authentication which can easily be deployed using the Openstack Charms.
confinement: strict
grade: stable

apps:
  s3test:
    command: s3test.py
    plugs: [network]

parts:
  main:
    plugin: dump
    source: .
    stage-packages: [python-keystoneclient, python-boto]
    override-build: |
     snapcraftctl build
     rm $SNAPCRAFT_PART_INSTALL/var/lib/ieee-data/mam.txt
     rm $SNAPCRAFT_PART_INSTALL/var/lib/ieee-data/oui36.txt
